using System.Reflection;

namespace ReelDiscovery.Helpers;

/// <summary>
/// Converts plain text email content to formatted HTML.
/// </summary>
public static class HtmlEmailFormatter
{
    private static string? _disclaimerBannerBase64;

    private const string EmailTemplate = @"<!DOCTYPE html>
<html>
<head>
    <meta charset=""utf-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
    <style>
        body {
            font-family: 'Segoe UI', Calibri, Arial, sans-serif;
            font-size: 11pt;
            line-height: 1.5;
            color: #1a1a1a;
            margin: 0;
            padding: 0;
            background-color: #ffffff;
        }
        .email-body {
            max-width: 800px;
            padding: 20px;
        }
        .signature {
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #e0e0e0;
            color: #444444;
            font-size: 10pt;
        }
        .signature-line {
            margin: 2px 0;
        }
        .quoted-content {
            margin-top: 20px;
            padding-left: 10px;
            border-left: 2px solid #0078d4;
            color: #505050;
        }
        .quoted-header {
            color: #0078d4;
            font-size: 10pt;
            margin-bottom: 10px;
        }
        .forward-header {
            margin-top: 20px;
            padding: 10px;
            background-color: #f5f5f5;
            border: 1px solid #e0e0e0;
            font-size: 10pt;
        }
        .forward-header-title {
            font-weight: bold;
            color: #0078d4;
            margin-bottom: 5px;
        }
        .forward-header-field {
            margin: 2px 0;
        }
        .forward-header-label {
            font-weight: bold;
            color: #505050;
        }
        p {
            margin: 0 0 10px 0;
        }
        .disclaimer-banner {
            width: 100%;
            max-width: 100%;
            height: auto;
            display: block;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <div class=""email-body"">
{CONTENT}
    </div>
    <img src=""data:image/png;base64,{BANNER_BASE64}"" alt=""QuikData Disclaimer - This email was generated by AI for demonstration purposes only"" class=""disclaimer-banner"" />
</body>
</html>";

    /// <summary>
    /// Converts plain text email body to formatted HTML.
    /// </summary>
    public static string ConvertToHtml(string plainText)
    {
        if (string.IsNullOrEmpty(plainText))
            return WrapInTemplate("<p></p>");

        // Split the email into parts: main content, quoted replies, forwarded content
        var (mainContent, quotedContent, isForward) = SplitEmailContent(plainText);

        var htmlContent = new System.Text.StringBuilder();

        // Format main content
        htmlContent.Append(FormatMainContent(mainContent));

        // Format quoted/forwarded content if present
        if (!string.IsNullOrEmpty(quotedContent))
        {
            if (isForward)
            {
                htmlContent.Append(FormatForwardedContent(quotedContent));
            }
            else
            {
                htmlContent.Append(FormatQuotedContent(quotedContent));
            }
        }

        return WrapInTemplate(htmlContent.ToString());
    }

    private static (string mainContent, string quotedContent, bool isForward) SplitEmailContent(string text)
    {
        // Look for forwarded message marker
        var forwardMarkers = new[]
        {
            "---------- Forwarded message ----------",
            "-------- Forwarded Message --------",
            "Begin forwarded message:"
        };

        foreach (var marker in forwardMarkers)
        {
            var forwardIndex = text.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
            if (forwardIndex > 0)
            {
                return (
                    text[..forwardIndex].TrimEnd(),
                    text[forwardIndex..],
                    true
                );
            }
        }

        // Look for quoted reply marker (On ... wrote:)
        var replyPatterns = new[]
        {
            "\n\nOn ",
            "\r\n\r\nOn "
        };

        foreach (var pattern in replyPatterns)
        {
            var replyIndex = text.IndexOf(pattern, StringComparison.OrdinalIgnoreCase);
            if (replyIndex > 0)
            {
                // Check if there's a "wrote:" after "On "
                var wroteIndex = text.IndexOf(" wrote:", replyIndex, StringComparison.OrdinalIgnoreCase);
                if (wroteIndex > replyIndex)
                {
                    return (
                        text[..replyIndex].TrimEnd(),
                        text[replyIndex..],
                        false
                    );
                }
            }
        }

        return (text, string.Empty, false);
    }

    private static string FormatMainContent(string content)
    {
        var lines = content.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
        var html = new System.Text.StringBuilder();
        var inSignature = false;
        var signatureBuffer = new System.Text.StringBuilder();

        for (int i = 0; i < lines.Length; i++)
        {
            var line = System.Net.WebUtility.HtmlEncode(lines[i]);

            // Detect signature start (common patterns)
            if (!inSignature && IsSignatureStart(lines, i))
            {
                inSignature = true;
                signatureBuffer.AppendLine("<div class=\"signature\">");
            }

            if (inSignature)
            {
                if (string.IsNullOrWhiteSpace(line))
                {
                    signatureBuffer.AppendLine("<div class=\"signature-line\">&nbsp;</div>");
                }
                else
                {
                    signatureBuffer.AppendLine($"<div class=\"signature-line\">{line}</div>");
                }
            }
            else
            {
                if (string.IsNullOrWhiteSpace(line))
                {
                    // Preserve blank lines as paragraph breaks
                    if (i > 0 && i < lines.Length - 1)
                    {
                        html.AppendLine("<p>&nbsp;</p>");
                    }
                }
                else
                {
                    html.AppendLine($"<p>{line}</p>");
                }
            }
        }

        if (inSignature)
        {
            signatureBuffer.AppendLine("</div>");
            html.Append(signatureBuffer);
        }

        return html.ToString();
    }

    private static bool IsSignatureStart(string[] lines, int index)
    {
        if (index >= lines.Length) return false;

        var line = lines[index].Trim();

        // Common signature delimiters
        if (line == "--" || line == "---" || line == "- -" || line.StartsWith("--"))
            return true;

        // Look for patterns like "Best regards," "Sincerely," etc. followed by a name
        var signoffPhrases = new[]
        {
            "Best regards",
            "Best,",
            "Regards,",
            "Sincerely,",
            "Thanks,",
            "Thank you,",
            "Cheers,",
            "Warm regards",
            "Kind regards",
            "All the best",
            "Take care",
            "Yours truly",
            "Respectfully",
            "Cordially"
        };

        foreach (var phrase in signoffPhrases)
        {
            if (line.StartsWith(phrase, StringComparison.OrdinalIgnoreCase))
            {
                // Check if there's content after this that looks like a signature
                // (name, title, phone number, etc.)
                if (index + 1 < lines.Length)
                {
                    var nextLine = lines[index + 1].Trim();
                    if (!string.IsNullOrEmpty(nextLine) && !nextLine.StartsWith(">"))
                    {
                        return true;
                    }
                }
                return true;
            }
        }

        return false;
    }

    private static string FormatQuotedContent(string quotedText)
    {
        var html = new System.Text.StringBuilder();
        var lines = quotedText.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);

        html.AppendLine("<div class=\"quoted-content\">");

        bool headerWritten = false;
        foreach (var rawLine in lines)
        {
            var line = rawLine.Trim();

            // First line with "On ... wrote:" becomes the header
            if (!headerWritten && line.StartsWith("On ") && line.Contains(" wrote:"))
            {
                html.AppendLine($"<div class=\"quoted-header\">{System.Net.WebUtility.HtmlEncode(line)}</div>");
                headerWritten = true;
                continue;
            }

            // Remove leading ">" from quoted lines
            var content = line.TrimStart('>', ' ');
            if (string.IsNullOrWhiteSpace(content))
            {
                html.AppendLine("<p>&nbsp;</p>");
            }
            else
            {
                html.AppendLine($"<p>{System.Net.WebUtility.HtmlEncode(content)}</p>");
            }
        }

        html.AppendLine("</div>");
        return html.ToString();
    }

    private static string FormatForwardedContent(string forwardedText)
    {
        var html = new System.Text.StringBuilder();
        var lines = forwardedText.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);

        html.AppendLine("<div class=\"forward-header\">");
        html.AppendLine("<div class=\"forward-header-title\">---------- Forwarded message ----------</div>");

        bool inHeader = true;
        var bodyContent = new System.Text.StringBuilder();

        foreach (var rawLine in lines)
        {
            var line = rawLine.Trim();

            // Skip the original marker line
            if (line.Contains("Forwarded message") || line.Contains("Begin forwarded message"))
                continue;

            // Header fields end with an empty line
            if (inHeader)
            {
                if (string.IsNullOrEmpty(line))
                {
                    inHeader = false;
                    html.AppendLine("</div>");
                    html.AppendLine("<div class=\"quoted-content\">");
                    continue;
                }

                // Parse header fields (From:, To:, Date:, Subject:)
                if (line.Contains(":"))
                {
                    var colonIndex = line.IndexOf(':');
                    var label = line[..colonIndex];
                    var value = line[(colonIndex + 1)..].Trim();
                    html.AppendLine($"<div class=\"forward-header-field\"><span class=\"forward-header-label\">{System.Net.WebUtility.HtmlEncode(label)}:</span> {System.Net.WebUtility.HtmlEncode(value)}</div>");
                }
            }
            else
            {
                if (string.IsNullOrWhiteSpace(line))
                {
                    bodyContent.AppendLine("<p>&nbsp;</p>");
                }
                else
                {
                    bodyContent.AppendLine($"<p>{System.Net.WebUtility.HtmlEncode(line)}</p>");
                }
            }
        }

        if (inHeader)
        {
            html.AppendLine("</div>");
            html.AppendLine("<div class=\"quoted-content\">");
        }

        html.Append(bodyContent);
        html.AppendLine("</div>");

        return html.ToString();
    }

    private static string WrapInTemplate(string content)
    {
        var bannerBase64 = GetDisclaimerBannerBase64();
        return EmailTemplate
            .Replace("{BANNER_BASE64}", bannerBase64)
            .Replace("{CONTENT}", content);
    }

    private static string GetDisclaimerBannerBase64()
    {
        if (_disclaimerBannerBase64 != null)
            return _disclaimerBannerBase64;

        try
        {
            // Load the banner image from embedded resources
            var assembly = Assembly.GetExecutingAssembly();
            var resourceName = "ReelDiscovery.Resources.quikdata_disclaimer_banner_yellow_svglogo_with_url.png";

            using var stream = assembly.GetManifestResourceStream(resourceName);
            if (stream != null)
            {
                using var ms = new MemoryStream();
                stream.CopyTo(ms);
                _disclaimerBannerBase64 = Convert.ToBase64String(ms.ToArray());
                return _disclaimerBannerBase64;
            }
        }
        catch
        {
            // Fall through to placeholder
        }

        // Return a minimal 1x1 transparent PNG if resource not found
        _disclaimerBannerBase64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=";
        return _disclaimerBannerBase64;
    }
}
